### ISSUE TITLE
Error on Compilation after adding audioplayer2 as a dependency

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [emostar/audioplayer#2]
> Launching lib/main.dart on iPhone 6 in debug mode...
> Running pod install...
> CocoaPods' output:
> ↳
>       Preparing
>     
>     Analyzing dependencies
>     
>     Inspecting targets to integrate
>       Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
>     
>     Fetching external sources
>     -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
>     -> Fetching podspec for `audioplayer2` from `.symlinks/plugins/audioplayer2/ios`
>     [!] No podspec found for `audioplayer2` in `.symlinks/plugins/audioplayer2/ios`
>     
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in `titled_section'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:697:in `fetch_external_source'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:673:in `block (2 levels) in fetch_external_sources'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `each'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `block in fetch_external_sources'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:671:in `fetch_external_sources'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'
> Error output from CocoaPods:
> ↳
>     
>     [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.
>     
>     [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> Error running pod install
> Error launching application on iPhone 6.

**Comment by emostar** [comment]
Does it work if you use the original repository, `audioplayer`?

**Comment by ThinkDigitalSoftware** [comment]
I assume so, that was the only change and it broke. I'll revert when I get
a chance.

**Comment by emostar** [comment]
I'll have access to a macbook over the weekend, so I can try to reproduce it and see what is going on then.

**Comment by ThinkDigitalSoftware** [comment]
It’s hard to revert cause the old one doesn’t accept the latest dart sdk

**Comment by ThinkDigitalSoftware** [comment]
OK, after reverting, the old one builds and runs.

**Comment by emostar** [comment]
It should be fixed in v0.5.2 ... can you try again? Thanks!
